name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
    build:
      runs-on: ${{ matrix.os }}
      strategy:
        matrix:
          os: [ubuntu-latest,macos-latest,windows-latest]
          build_type: [Release, Debug]

      steps:
        - name: checkout code
          uses: actions/checkout@v3

        - name: Install Dependencies (Linux)
          if: runner.os == 'Linux'
          run: |
            sudo apt-get update
            sudo apt-get install -y libgtest-dev
            cd /usr/src/gtest
            sudo cmake .
            sudo make
            sudo make install

        - name: Setup Environment (MacOS)
          if: runner.os == 'macOS'
          run: |
            brew install googletest

        - name: Setup Environment (Windows)
          if: runner.os == 'Windows'
          run: |
            choco install googletest

        - name: Create Build Directory
          run: mkdir build

        - name: Configure CMake
          run: cd build && cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

        - name: Build
          run: cd build && cmake --build . --config ${{ matrix.build_type }}

        - name: Run Tests
          run: cd build && ctest -C ${{ matrix.build_type }}
